### PR TITLE
fix: use url.URL to encode and decode PURLs

### LINKED ISSUE #51: purl with name contain whitespace can not be built from purl string
```go
import (
	"testing"

	"github.com/package-url/packageurl-go"
)

func TestPURL(t *testing.T) {
	p := packageurl.NewPackageURL("generic", "", "a b", "", nil, "")
	u := p.ToString()
	got, err := packageurl.FromString(u)
	t.Log(err)              // <nil>
	t.Log(p.Name, got.Name) // a b a+b
}
```

### PR DESCRIPTION
**Pull request by tommyknows**
This commit refactors the `ToString` and `FromString` functions / methods to use the `url.URL` type, instead of trying to parse URLs directly.

The [PURL Spec](https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst#a-purl-is-a-url) explicitly says:

> A purl is a URL:
> A purl is a valid URL and URI that conforms to the URL definitions or
> specifications ...

So why not actually use Go's URL type to do operations on it?

This commit does exactly that, and removes a lot of the previously dense parsing-logic with simpler checks based on the URL's fields. Especially `ToString()` has gotten a lot simpler through that.

Additionaly, by switching to the URL package, this commit fixes a couple of outstanding bugs:
- When a qualifier contained `+` signs, which are valid in URL paths, but not in URL queries, the sign did not get escaped. The previous code relied on `url.PathUnescape` to unescape keys and values, which should have used `url.QueryUnescape` instead. Further, encoding Qualifiers used `url.PathEscape` instead of `url.QueryEscape`. This could have led to pURLs losing `+` signs if they were properly encoded.
- Fixes #51, where spaces in names have not gotten encoded correctly.
- Fixes most test-cases from #22 / #23 that are round-trip-save (e.g. all cases where input == output), except the "pre-encoded qualifier value is unchanged" testcase that is wrong - a qualifier shouldn't be encoded with `%20` for a space, but with a plus-sign (query encoding).
- Fixes most cases from #41 as well, except:
  -  where the query encoding in the test-cases are wrong (" " -> "+", "+" -> "%20") (test-cases `pre-encoded_qualifier_value_is_unchanged` and `unencoded_qualifier_value_is_encoded`),
  - `characters_are_unencoded_where_allowed`: `<` should be encoded, as far as I can tell. The Go stdlib also encodes it, so this should be fine.
  - `explicit_characters_are_encoded`: `@` does not need to be encoded.

When reading through that list and all the nuances, it makes it clear that we shouldn't do this ourselves! And this commit doesn't, it simply relies on the Go standard library to handle all of these cases correctly.

All of the aforementioned issues should have test-cases, presumably added to the test-suite-data.

----

You may notice that this code barely touches the tests. I'm not sure whether to add explicit test-cases to the Go implementation only, or if these should rather be added to the general test-suite. I'm happy to do either way - I've ensured that these changes work with all the tests from the issues & PRs mentioned above.

The only thing that does change to the test-suite is to use a multi-line matching for the JSON-data, so that not only `{"key": "value"}` qualifiers are valid, but also:
```json
{
  "key": "value"
}
```

(not that it's currently needed, but when I added tests my editor automatically made multi-line strings out of these, so I needed to fix it 🙂)

### CODE REVIEW

**Comment by shibumi** [comment]
Hi @tommyknows 👋

First all thank you for your contribution. I totally agree with you here. If purls are considered URLs we should try using the go url package.

There are a few test cases failing, can you have a look at this?

**Comment by tommyknows** [comment]
Hi @shibumi, thanks, should be fixed! Missed to lowercase the type before giving it to the normalisation-functions :)

File: packageurl.go [hunk 1]
```diff
@@ -120,6 +121,15 @@ func (q Qualifier) String() string {
 // in the package URL.
 type Qualifiers []Qualifier
 
+// urlQuery returns a raw URL query with all the qualifiers as keys + values.
+func (q Qualifiers) urlQuery() (rawQuery string) {
```
Comment (shibumi) [inline packageurl.go:125]: You define `rawQuery` as return value, but I do not see it in the function. Is this a mistake?

File: packageurl.go [hunk 2]
```diff
@@ -184,39 +194,20 @@ func NewPackageURL(purlType, namespace, name, version string,
...
-	if p.Subpath != "" {
-		purl = purl + "#" + p.Subpath
-	}
-	return purl
+	// we use JoinPath and EscapePath as the behavior for "/" is only correct with that.
+	// We don't want to escape "/", but want to escape all other characters that are necessary.
+	u = u.JoinPath(p.Type, p.Namespace, strings.Join([]string{p.Name, p.Version}, "@"))
+	// write the actual path into the "Opaque" block, so that the generated string at the end is
+	// pkg:<path> and not pkg://<path>.
+	u.Opaque, u.Path = u.EscapedPath(), ""
```
Comment (shibumi) [inline packageurl.go:208]: Why do we explicitly set u.Path to an empty string?

File: packageurl_test.go [hunk 3]
```diff
@@ -55,7 +55,7 @@ type OrderedMap struct {
 
 // qualifiersMapPattern is used to parse the TestFixture "qualifiers" field to
 // ensure that it's a json object.
-var qualifiersMapPattern = regexp.MustCompile(`^\{.*\}$`)
+var qualifiersMapPattern = regexp.MustCompile(`(?ms)^\{.*\}$`)
```
Comment (shibumi) [inline packageurl_test.go:58]: `?s` will lead to matching new lines. It doesn't look like we did this before. Can you explain your intention behind this change? :)

**Comment by shibumi** [comment]
Added a few comments, mostly nit picks

File: packageurl.go (hunk 1 above)
Comment (tommyknows) [reply packageurl.go:125]: Simply for documentational reasons - the code doesn‘t need it. It‘s nice to just read the function header and know what it does.

that said - I‘m not particularly attached to it, I can remove it if you prefer :)

File: packageurl.go (hunk 2 above)
Comment (tommyknows) [reply packageurl.go:208]: Seems like it‘s technically not necessary, you‘re right:
https://go.dev/play/p/XqKNeqpDsrt

But i‘m not sure if the fact that u.Path is ignored if u.Opaque is set is „expected behavior“ or just an implementation detail.

The emptry string assignments makes it more obvious without knowing that :)

File: packageurl_test.go (hunk 3 above)
Comment (tommyknows) [reply packageurl_test.go:58]: I‘ve described the intention n the PR description:

The only thing that does change to the test-suite is to use a multi-line matching for the JSON-data, so that not only `{"key": "value"}` qualifiers are valid, but also:
```json
{
  "key": "value"
}
```

(not that it's currently needed, but when I added tests my editor automatically made multi-line strings out of these, so I needed to fix it 🙂)

**Review by shibumi — APPROVED** [review]

**Comment by shibumi** [comment]
Thank you for contribution @tommyknows , great work!! 💯
